#!/usr/bin/env node

var path = require('path');
var mysql = require('mysql');
var fs = require('fs');
var request = require("request");

var dbContent = fs.readFileSync(__dirname + "/database.json", "utf8");
var databaseCfg = JSON.parse(dbContent);
var dev = databaseCfg.development;

var connection = mysql.createConnection({
  host     : dev.host,
  user     : dev.user,
  password : dev.password,
  database: dev.database
});

connection.connect();

function setExpired(id) {
  connection.query("update invoices set state = \"" + "expired" + "\" where id=?", id, function(err, result){

  });
}

connection.query("select * from invoices where state = \""+ "unpay" +"\"", {}, function(err, result){
  console.log(result);
  if (result.length > 0){
    for (var i = 0; i < result.length; i++) {
      var ele = result[i];

      request('https://blockchain.info/q/addressbalance/asfdfgdgdgjshdkhskdhgxcvdgdsgf?confirmations=1', function (error, response, body) {
        // console.log(error);
        // console.log(response);
        var now = 1432424234;
        var created = ele.created_at;
        
        // TODO: 检查付款成功, 并发送第三封邮件
        if (!error && response.statusCode == 200) {
          console.log(body) // Show the body.
        } else if (now - created > 24 * 3600) {
          setExpired(ele.id);
        }

      })

    }
  }
});

connection.end();
