#!/usr/bin/env node

var path = require('path');
var mysql = require('mysql');
var fs = require('fs');

var dbContent = fs.readFileSync(__dirname + "/database.json", "utf8");
var databaseCfg = JSON.parse(dbContent);
var dev = databaseCfg.development;

var connection = mysql.createConnection({
  host     : dev.host,
  user     : dev.user,
  password : dev.password,
  database: dev.database
});

connection.connect();

function setExpired(id) {
  connection.query("update invoices set state = \"" + "expired" + "\" where id=?", id, function(err, result){

  });
}

connection.query("select * from invoices where state = \""+ "unpay" +"\"", {}, function(err, result){
  console.log(result);
  if (result.length > 0){
    for (var i = 0; i < result.length; i++) {
      var ele = result[i];

      var now = 1432424234;
      var created = ele.created_at;
      if (now - created > 24 * 3600) {
        setExpired(ele.id);
      }
    }
  }
});

connection.end();
