#!/usr/bin/env node

var mysql = require('mysql');
var fs = require('fs');
var dateFormat = require('dateformat');
var config = require('./config/config')

var bitcoin_address_path = config.bitcoin_address_path;
var ether_address_path = config.ether_address_path;

// mysql init
var dbContent = fs.readFileSync(__dirname + "/database.json", "utf8");
var databaseCfg = JSON.parse(dbContent);
var dev = databaseCfg.development;
var connection = mysql.createConnection({
  host     : dev.host,
  user     : dev.user,
  password : dev.password,
  database: dev.database
});

var connection1 = mysql.createConnection({
  host     : dev.host,
  user     : dev.user,
  password : dev.password,
  database: dev.database
});

function insertDbBitcoin(address, category) {
  connection.connect();
  var date = new Date();
  var date = dateFormat(date, "yyyy-mm-dd h:MM:ss");

  for (var i = 0; i < address.length; i++) {
    var addr = address[i];
    var sql = "insert into address(hash_code, category, created_at,updated_at) values(\"" + addr + "\", \"" +  category + "\", \"" + date +"\", \""+ date +"\")";
    connection.query(sql, function(err, result){
      console.log(err);
      console.log(result);
    })
  }
  connection.end();
}

function insertDbEther(address, category) {
  connection1.connect();
  var date = new Date();
  var date = dateFormat(date, "yyyy-mm-dd h:MM:ss");

  for (var i = 0; i < address.length; i++) {
    var addr = address[i];
    var sql = "insert into address(hash_code, category, created_at,updated_at) values(\"" + addr + "\", \"" +  category + "\", \"" + date +"\", \""+ date +"\")";
    connection1.query(sql, function(err, result){
      console.log(err);
      console.log(result);
    })
  }
  connection1.end();
}

fs.readFile(bitcoin_address_path, 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  var array = data.toString().split("\n");

  console.log(array);

  insertDbBitcoin(array, "bitcoin");
  return;
});

fs.readFile(ether_address_path, 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  var array = data.toString().split("\n");

  console.log(array);

  insertDbEther(array, "ether");
  return;
});
