#!/usr/bin/env node

var mysql = require('mysql');
var fs = require('fs');
var dateFormat = require('dateformat');
var config = require('./config/config')

var address_path = config.address_path;

// mysql init
var dbContent = fs.readFileSync(__dirname + "/database.json", "utf8");
var databaseCfg = JSON.parse(dbContent);
var dev = databaseCfg.development;
var connection = mysql.createConnection({
  host     : dev.host,
  user     : dev.user,
  password : dev.password,
  database: dev.database
});

function insertDB(address) {
  connection.connect();
  var date = new Date();
  var date = dateFormat(date, "yyyy-mm-dd h:MM:ss");

  for (var i = 0; i < address.length; i++) {
    var addr = address[i];
    var sql = "insert into address(hash_code,created_at,updated_at) values(\"" + addr + "\", \"" + date +"\", \""+ date +"\")";
    connection.query(sql, function(err, result){
      console.log(err);
      console.log(result);
    })
  }
  connection.end();
}

fs.readFile(address_path, 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  var array = data.toString().split("\n");

  console.log(array);

  insertDB(array);
  return;
});
